DROP DATABASE IF EXISTS Esame;
CREATE DATABASE Esame;
USE Esame;

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    age INT
);
