INSERT INTO users (name, email, age) VALUES
('Luca Bianchi', 'luca.bianchi@example.com', 28),
('Giulia Rossi', 'giulia.rossi@example.com', 32),
('Marco Verdi', 'marco.verdi@example.com', 24),
('Elena Neri', 'elena.neri@example.com', 27),
('Francesco Gallo', 'francesco.gallo@example.com', 45),
('Chiara Fontana', 'chiara.fontana@example.com', 30),
('Davide Russo', 'davide.russo@example.com', 26),
('Sara Colombo', 'sara.colombo@example.com', 38),
('Andrea Riva', 'andrea.riva@example.com', 22),
('Martina Greco', 'martina.greco@example.com', 34),
('Stefano Leone', 'stefano.leone@example.com', 29),
('Laura Villa', 'laura.villa@example.com', 36),
('Alessandro Conti', 'alessandro.conti@example.com', 33),
('Valentina Marchetti', 'valentina.marchetti@example.com', 25),
('Matteo Ferri', 'matteo.ferri@example.com', 31),
('Federica De Luca', 'federica.deluca@example.com', 23),
('Simone Marino', 'simone.marino@example.com', 40),
('Beatrice Caruso', 'beatrice.caruso@example.com', 21),
('Giorgio Barone', 'giorgio.barone@example.com', 37),
('Ilaria Fabbri', 'ilaria.fabbri@example.com', 35);
