DROP DATABASE IF EXISTS Progetto;
CREATE DATABASE IF NOT EXISTS Progetto;

USE Progetto;

CREATE TABLE IF NOT EXISTS utente(
id_utente BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255),
cognome VARCHAR(255),
telefono VARCHAR (30),
email VARCHAR(255)
);